# Generated by Django 3.0.4 on 2020-03-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='logoinfo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('img1name', models.CharField(default='', max_length=255)),
                ('img1', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('img2name', models.CharField(default='', max_length=255)),
                ('img2', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('img3name', models.CharField(default='', max_length=255)),
                ('img3', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('img4name', models.CharField(default='', max_length=255)),
                ('img4', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('img5name', models.CharField(default='', max_length=255)),
                ('img5', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
