# Generated by Django 3.0.4 on 2020-03-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_logoinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logoinfo',
            new_name='appinfo',
        ),
    ]
