# Generated by Django 3.0.4 on 2020-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200320_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('companyname', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('contact', models.IntegerField()),
                ('message', models.TextField()),
                ('appid', models.IntegerField(default=0)),
                ('appimg', models.ImageField(default='', upload_to='upload/')),
            ],
        ),
    ]
