# Generated by Django 3.0.4 on 2020-03-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='appid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appinfo'),
        ),
    ]
