# Generated by Django 3.0.4 on 2020-03-25 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200322_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('password', models.TextField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='datetime',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
