# Generated by Django 3.0.4 on 2020-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200325_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mark_time',
            field=models.IntegerField(default=0),
        ),
    ]
